AddDuration=false
AddPoVProf=false
ApplicationTraces=false
AutoAdd=false
AutoAddPath=
AutoDiscordBatch=false
AutoParse=false
CompressRaw=false
ComputeDamageModifiers=true
CustomTooShort=2200
DetailledWvW=true
DPSReportUserToken=
HtmlCompressJson=false
HtmlExternalScripts=false
HtmlExternalScriptsCdn=
HtmlExternalScriptsPath=
IndentJSON=false
LightTheme=false
MemoryLimit=0
OutLocation=__OUTLOCATION__
ParseCombatReplay=true
ParseMultipleLogs=false
ParsePhases=true
PopulateHourLimit=0
RawTimelineArrays=true
SaveAtOut=false
SaveOutCSV=false
SaveOutHTML=false
SaveOutJSON=true
SaveOutTrace=false
SendEmbedToWebhook=false
SendSimpleMessageToWebhook=false
SingleThreaded=false
SkipFailedTries=false
UploadToWingman=false
WebhookURL=
