AddDuration=False
AddPoVProf=False
Anonymous=False
ApplicationTraces=False
AutoAdd=False
AutoAddPath=
AutoDiscordBatch=False
AutoParse=False
CompressRaw=True
ComputeDamageModifiers=True
CustomTooShort=2200
DetailledWvW=True
DPSReportUserToken=
HtmlCompressJson=False
HtmlExternalScripts=False
HtmlExternalScriptsCdn=
HtmlExternalScriptsPath=
IndentJSON=False
LightTheme=False
MemoryLimit=0
Outdated=False
OutLocation=__OUTLOCATION__
ParseCombatReplay=True
ParseMultipleLogs=True
ParsePhases=True
PopulateHourLimit=0
RawTimelineArrays=True
SaveAtOut=False
SaveOutCSV=False
SaveOutHTML=False
SaveOutJSON=True
SaveOutTrace=True
SendEmbedToWebhook=False
SendSimpleMessageToWebhook=False
SingleThreaded=False
SkipFailedTries=False
UpdateAvailable=False
UpdateLastChecked=1764908827
UploadToDPSReports=True
UploadToWingman=False
WebhookURL=
